# (optional) Redis configuration
redis_host:
redis_port:
redis_password:
redis_db:

# Safe mode (if True)
nobroadcast: False

# Wallet passphrase of pypeerplays
passphrase: super-secret-wallet-passphrase

# Proposer account
BOOKIE_PROPOSER: init0

# Approver account
BOOKIE_APPROVER: init0

# Default mail destination on errors
mailto: info@example.com

# Notifications via telgram
telegram_token:

# python3 -m telegram_handler "${telegram_token}"
telegram_chatid:
