# (optional) Redis configuration
redis_host:
redis_port:
redis_password:
redis_db:

# Safe mode (if True)
nobroadcast: False

# Wallet passphrase of pypeerplays
passphrase: super-secret-wallet-passphrase

# Proposer account
BOOKIE_PROPOSER: init0

# Approver account
BOOKIE_APPROVER: init0
